In [1]:
import numpy as np

In [6]:
x = np.array([[1, 3], [2, 4]])
y = np.array([[2, 8], [1, 2]])
print(x)
print(y)

[[1 3]
 [2 4]]
[[2 8]
 [1 2]]


In [7]:
print(x + y)
print(np.add(x, y))

[[ 3 11]
 [ 3  6]]
[[ 3 11]
 [ 3  6]]


In [8]:
print(x - y)
print(np.subtract(x, y))

[[-1 -5]
 [ 1  2]]
[[-1 -5]
 [ 1  2]]


In [9]:
print(x * y)
print(np.multiply(x, y))

[[ 2 24]
 [ 2  8]]
[[ 2 24]
 [ 2  8]]


In [10]:
print(x / y)
print(np.divide(x, y))

[[0.5   0.375]
 [2.    2.   ]]
[[0.5   0.375]
 [2.    2.   ]]


In [12]:
print(np.power(x, y))

[[   1 6561]
 [   2   16]]


In [13]:
print(np.exp(x))

[[ 2.71828183 20.08553692]
 [ 7.3890561  54.59815003]]


In [14]:
print(np.sqrt(x))

[[1.         1.73205081]
 [1.41421356 2.        ]]


In [15]:
print(x)
print(x + 3)
print(x - 3)
print(x * 3)
print(x / 3)

[[1 3]
 [2 4]]
[[4 6]
 [5 7]]
[[-2  0]
 [-1  1]]
[[ 3  9]
 [ 6 12]]
[[0.33333333 1.        ]
 [0.66666667 1.33333333]]


In [16]:
print(np.add(x, 3))
print(np.subtract(x, 3))
print(np.multiply(x, 3))
print(np.divide(x, 3))

[[4 6]
 [5 7]]
[[-2  0]
 [-1  1]]
[[ 3  9]
 [ 6 12]]
[[0.33333333 1.        ]
 [0.66666667 1.33333333]]


In [18]:
z = np.array([2,4])
print(x)
print(x + z)
print(np.add(x, z))

[[1 3]
 [2 4]]
[[3 7]
 [4 8]]
[[3 7]
 [4 8]]


In [19]:
w = np.array([[2],[6]])
print(x)
print(x + w)
print(np.add(x, w))

[[1 3]
 [2 4]]
[[ 3  5]
 [ 8 10]]
[[ 3  5]
 [ 8 10]]


In [25]:
x = np.arange(9).reshape((3, 3))
print(x)
print(np.median(x, axis=0))
print(np.median(x, axis=1))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[3. 4. 5.]
[1. 4. 7.]


In [32]:
x = np.full((4, 4), 1)
y = np.arange(1,5)
print(x)
print(y)
print(x * y)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[1 2 3 4]
[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]
