In [1]:
import numpy as np

In [2]:
x = np.arange(0, 20).reshape((4,5))
print(x)


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [4]:
y = x[(x > 10) & (x < 15)]
print(y)

[11 12 13 14]


In [8]:
print((x < 10) | (x > 15))

[[ True  True  True  True  True]
 [ True  True  True  True  True]
 [False False False False False]
 [False  True  True  True  True]]


In [11]:
x = np.array([1, 4, 5, 6, 8])
y = np.array([6 ,8 ,3, 1, 0])
print(np.intersect1d(x, y))
print(np.setdiff1d(x, y))
print(np.union1d(x,y))

[1 6 8]
[4 5]
[0 1 3 4 5 6 8]


In [17]:
x = np.random.randint(1, 10, 15)


In [19]:
print(x)
print(np.sort(x))
print(np.sort(np.unique(x)))
print(x)
x.sort()
print(x)

[1 1 1 3 3 4 4 5 6 6 7 7 8 8 9]
[1 1 1 3 3 4 4 5 6 6 7 7 8 8 9]
[1 3 4 5 6 7 8 9]
[1 1 1 3 3 4 4 5 6 6 7 7 8 8 9]
[1 1 1 3 3 4 4 5 6 6 7 7 8 8 9]


In [20]:
x = np.random.randint(0, 10, (5,5))
print(x)

[[0 8 8 8 1]
 [4 6 5 7 3]
 [4 7 3 3 8]
 [5 2 0 4 8]
 [2 7 9 2 7]]


In [22]:
y = np.sort(x, axis=0)
print(y)

[[0 2 0 2 1]
 [2 6 3 3 3]
 [4 7 5 4 7]
 [4 7 8 7 8]
 [5 8 9 8 8]]


In [23]:
y = np.sort(x, axis=1)
print(y)

[[0 1 8 8 8]
 [3 4 5 6 7]
 [3 3 4 7 8]
 [0 2 4 5 8]
 [2 2 7 7 9]]


In [25]:
x.sort(axis=0)
x.sort(axis=1)
print(x)

[[0 0 1 2 2]
 [2 3 3 3 6]
 [4 4 5 7 7]
 [4 7 7 8 8]
 [5 8 8 8 9]]
