In [1]:
import numpy as np

In [2]:
x = np.array([1,2,3,4], dtype=float)
print(x)

[1. 2. 3. 4.]


In [3]:
y = np.reshape(x, (2,2))
print(y)

[[1. 2.]
 [3. 4.]]


In [4]:
print(x)

[1. 2. 3. 4.]


In [7]:
x = np.zeros(6, dtype=int)
print(x)

[0 0 0 0 0 0]


In [9]:
x = np.ones(6, dtype=int)
print(x)

[1 1 1 1 1 1]


In [18]:
x = np.full(7, 1.2)
print(x)

[1.2 1.2 1.2 1.2 1.2 1.2 1.2]


In [22]:
x = np.arange(1, 7, 2)
print(x)

[1 3 5]


In [25]:
x = np.linspace(0, 10, 10, endpoint=False).reshape(2,5)
print(x)

[[0. 1. 2. 3. 4.]
 [5. 6. 7. 8. 9.]]


In [31]:
x = np.eye(5)
y = np.diag([1,2,3,4])
print(x)
print(y)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
