In [1]:
import numpy as np

In [14]:
x = np.array([[1,2,3], [4,5,6]])
print(x)

[[1 2 3]
 [4 5 6]]


In [5]:
print(x.ndim)
print(x.shape)
print(x.dtype)

2
(2, 3)
int32


In [15]:
print(type(x))

<class 'numpy.ndarray'>


In [7]:
np.save('my_array', x)

In [9]:
y = np.load('my_array.npy')
print(y)

[[1 2 3]
 [4 5 6]]


In [10]:
z = np.array([1,2,3])
np.save('my_array', z)

In [11]:
y = np.load('my_array.npy')
print(y)

[1 2 3]


In [12]:
y = np.load('my_array.npy')
print(y)

[1 2 3]


In [13]:
x.size

6

In [21]:
x = np.random.random(size=(2,3,2)).reshape(12)
print(x)

[0.95845806 0.65667713 0.80985029 0.70877552 0.31753886 0.47813014
 0.53199259 0.13738223 0.21922818 0.65550008 0.75769801 0.99774457]


In [27]:
x = np.random.randint(2, 6, size=(2,3))
print(x)

[[4 2 5]
 [5 2 4]]


In [33]:
x = np.random.normal(0, 0.1, (1000, 1000))
print(x)

[[-0.02150517  0.02936372  0.04552227 ...  0.10406454  0.09979496
  -0.14895806]
 [-0.06239108  0.01445276  0.09484425 ... -0.00074596 -0.1219123
  -0.04814216]
 [-0.10078584  0.00237497 -0.07520956 ... -0.03530258 -0.02412518
   0.11833599]
 ...
 [-0.07707534  0.03968307  0.07396253 ... -0.1101479  -0.05694265
   0.05606684]
 [-0.10717433  0.10376439 -0.14621121 ... -0.24369017 -0.1322489
   0.04084154]
 [-0.12763616 -0.00710279 -0.17604538 ...  0.12347422 -0.10845539
   0.09923207]]


In [39]:
print('Mean: ', x.mean())
print('Std: ', x.std())
print('Max: ', x.max())
print('Min: ', x.min())
print('# positive: ', (x > 0))
print('# negative: ', (x < 0).sum())

Mean:  -0.00010455818507884384
Std:  0.10017394208987802
Max:  0.5025985194619054
Min:  -0.5015702353449126
# positive:  [[False  True  True ...  True  True False]
 [False  True  True ... False False False]
 [False  True False ... False False  True]
 ...
 [False  True  True ... False False  True]
 [False  True False ... False False  True]
 [False False False ...  True False  True]]
# negative:  500681
