In [1]:
import numpy as np

In [5]:
x = np.arange(1,21).reshape(4,5)
print(x)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [6]:
y = x[2:4, 2:5]
print(y)

[[13 14 15]
 [18 19 20]]


In [7]:
y = x[1:, 2:]
print(y)

[[ 8  9 10]
 [13 14 15]
 [18 19 20]]


In [8]:
y = x[0:3, 0:3]
print(y)

[[ 1  2  3]
 [ 6  7  8]
 [11 12 13]]


In [9]:
y = x[:3,:3]
print(y)

[[ 1  2  3]
 [ 6  7  8]
 [11 12 13]]


In [10]:
y = x[: , 0:1]
print(y)

[[ 1]
 [ 6]
 [11]
 [16]]


In [11]:
y = x[: , 0]
print(y)

[ 1  6 11 16]


In [14]:
y = x[0:1, :]
print(y)

[[1 2 3 4 5]]


In [15]:
y[0, 1] = 10
print(x)

[[ 1 10  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [16]:
y = x[:3, :3].copy()
y[1,1] = 10
print(y)
print(x)

[[ 1 10  3]
 [ 6 10  8]
 [11 12 13]]
[[ 1 10  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [17]:
y = np.copy(x[:3, :3])
y[0, 0] = 1000
print(y)
print(x)

[[1000   10    3]
 [   6    7    8]
 [  11   12   13]]
[[ 1 10  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [23]:
z = np.diag(x)
print(z)

[ 1  7 13 19]


In [24]:
z = np.diag(x, k=1)
print(z)
z =np.diag(x, k= -1)
print(z)

[10  8 14 20]
[ 6 12 18]


In [29]:
x = np.random.randint(0, 6, (3,3))
print(x)
y = np.unique(x)
print(y)

[[5 0 5]
 [3 2 3]
 [1 4 3]]
[0 1 2 3 4 5]
