In [2]:
import numpy as np

In [12]:

print(x[5])

6


In [13]:
x = np.arange(10).reshape(2,5)
print(x)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [14]:
print(x[0, 4])

4


In [15]:
x = np.arange(27).reshape(3,3,3)
print(x)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [18]:
x[0, 0, 1] = 10
print(x)

[[[ 0 10  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [23]:
x = np.array([1,2,3,4,5,6])
y = np.delete(x, [1,2])
print(x)
print(y)

[1 2 3 4 5 6]
[1 4 5 6]


In [32]:
x = np.arange(0, 10).reshape(2,5)
print(x)
y = np.delete(x, 1, axis=0)
print(y)

z = np.delete(x, [1,2], axis = 1)
print(z)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1 2 3 4]]
[[0 3 4]
 [5 8 9]]


In [34]:
x = np.arange(27).reshape(3,3,3)
print(x)

y = np.delete(x, 0, axis=0)
print(y)

z = np.delete(x, [0, 2], axis=1)
print(z)

w = np.delete(x, [0,1], axis=2)
print(w)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
[[[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
[[[ 3  4  5]]

 [[12 13 14]]

 [[21 22 23]]]
[[[ 2]
  [ 5]
  [ 8]]

 [[11]
  [14]
  [17]]

 [[20]
  [23]
  [26]]]


In [47]:
x = np.arange(0, 10).reshape(2,5)
print(x)

y = np.append(x, [[1,2,3,4,5]], axis=0)
print(y)

z = np.append(x, [[3],[4]], axis=1)
print(z)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 2 3 4 5]]
[[0 1 2 3 4 3]
 [5 6 7 8 9 4]]


In [43]:
x = np.arange(10)
print(x)

y = np.insert(x, 3, [1,2])
print(y)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 1 2 3 4 5 6 7 8 9]


In [56]:
x = np.reshape(x, (2,5))
print(x)
y = np.insert(x, 1, [1,2,3,4,5], axis=0)
print(y)
z = np.insert(x, 2, [3,4],axis=1)
print(z)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1 2 3 4]
 [1 2 3 4 5]
 [5 6 7 8 9]]
[[0 1 3 2 3 4]
 [5 6 4 7 8 9]]


In [70]:
x = np.arange(6).reshape(2,3)
print(x)

y = np.vstack((x, [[1,2,3]]))
print(y)

z = np.hstack((x,[[1],[2]]))
print(z)

[[0 1 2]
 [3 4 5]]
[[0 1 2]
 [3 4 5]
 [1 2 3]]
[[0 1 2 1]
 [3 4 5 2]]
